plugins {
    id 'org.springframework.boot' version '3.4.0'
    id 'java'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'com.eureka'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '21'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.4.0')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    
    // Spring Data JPA & In-Memory H2 Database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.h2database:h2'

    // Spring Kafka for Ingestion Pipeline
    implementation 'org.springframework.kafka:spring-kafka'
    
    // gRPC and Protobuf
    implementation 'io.grpc:grpc-netty-shaded:1.62.2'
    implementation 'io.grpc:grpc-protobuf:1.62.2'
    implementation 'io.grpc:grpc-stub:1.62.2'
    compileOnly 'org.glassfish:javax.annotation:10.0-b28'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.1"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.62.2"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir '../proto'
        }
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

// Custom tasks to compile and build the frontend React application
task npmInstall(type: Exec) {
    workingDir 'frontend'
    inputs.file('frontend/package.json')
    outputs.dir('frontend/node_modules')
    
    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'npm.cmd', 'install'
    } else {
        commandLine 'zsh', '-l', '-c', 'npm install'
    }
}

task npmBuild(type: Exec) {
    dependsOn npmInstall
    workingDir 'frontend'
    inputs.dir('frontend/src')
    inputs.file('frontend/package.json')
    inputs.file('frontend/tsconfig.json')
    inputs.file('frontend/vite.config.ts')
    inputs.file('frontend/index.html')
    outputs.dir('frontend/dist')

    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'npm.cmd', 'run', 'build'
    } else {
        commandLine 'zsh', '-l', '-c', 'npm run build'
    }
}

task copyFrontendToStatic(type: Copy) {
    dependsOn npmBuild
    from 'frontend/dist'
    into 'src/main/resources/static'
}

processResources.dependsOn copyFrontendToStatic

clean {
    delete 'src/main/resources/static'
    delete 'frontend/dist'
}
